# Generated by Django 5.2.3 on 2025-06-20 10:17

import api.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('roll_number', models.CharField(max_length=20, unique=True)),
                ('contact', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Contact number must be 10 digits.', regex='^\\d{10}$')])),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('ldap_id', models.CharField(max_length=50, unique=True)),
                ('department', models.CharField(choices=[('aerospace_engineering', 'Aerospace Engineering'), ('chemical_engineering', 'Chemical Engineering'), ('civil_engineering', 'Civil Engineering'), ('computer_science_engineering', 'Computer Science and Engineering'), ('electrical_engineering', 'Electrical Engineering'), ('engineering_physics', 'Engineering Physics'), ('materials_science_engineering', 'Materials Science and Engineering'), ('mechanical_engineering', 'Mechanical Engineering'), ('metallurgical_engineering', 'Metallurgical Engineering and Materials Science'), ('mathematics_statistics', 'Mathematics and Statistics'), ('chemistry', 'Chemistry'), ('physics', 'Physics'), ('biosciences_bioengineering', 'Biosciences and Bioengineering'), ('earth_sciences', 'Earth Sciences'), ('energy_science_engineering', 'Energy Science and Engineering'), ('environmental_science_engineering', 'Environmental Science and Engineering'), ('industrial_design_centre', 'Industrial Design Centre'), ('systems_control_engineering', 'Systems and Control Engineering'), ('climate_studies', 'Climate Studies'), ('other', 'Other')], max_length=50)),
                ('year_of_study', models.CharField(choices=[('1st_year', '1st Year'), ('2nd_year', '2nd Year'), ('3rd_year', '3rd Year'), ('4th_year', '4th Year'), ('5th_year', '5th Year'), ('phd', 'PhD'), ('msc', 'MSc'), ('mtech', 'MTech')], max_length=20)),
                ('payment_screenshot', models.ImageField(upload_to=api.models.upload_payment_screenshot)),
                ('payment_verified', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'rejected'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('confirmation_accepted', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program_attended', models.BooleanField(default=False)),
                ('refund_processed', models.BooleanField(default=False)),
                ('refund_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Shadow Program Registration',
                'verbose_name_plural': 'Shadow Program Registrations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RegistrationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_open', models.BooleanField(default=True)),
                ('registration_fee', models.DecimalField(decimal_places=2, default=50.0, max_digits=6)),
                ('max_registrations', models.PositiveIntegerField(blank=True, null=True)),
                ('program_date', models.DateTimeField(blank=True, null=True)),
                ('payment_qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('payment_instructions', models.TextField(default='Scan the QR code and pay ₹50')),
            ],
            options={
                'verbose_name': 'Registration Settings',
                'verbose_name_plural': 'Registration Settings',
            },
        ),
    ]
