# Generated by Django 5.2.3 on 2025-08-23 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='department',
            field=models.CharField(choices=[('aerospace_engineering', 'Aerospace Engineering'), ('applied geophysics', 'Applied Geophysics'), ('chemical_engineering', 'Chemical Engineering'), ('civil_engineering', 'Civil Engineering'), ('computer_science_engineering', 'Computer Science and Engineering'), ('electrical_engineering', 'Electrical Engineering'), ('engineering_physics', 'Engineering Physics'), ('mechanical_engineering', 'Mechanical Engineering'), ('metallurgical_engineering', 'Metallurgical Engineering and Materials Science'), ('mathematics', 'Mathematics'), ('chemistry', 'Chemistry'), ('physics', 'Physics'), ('biosciences_bioengineering', 'Biosciences and Bioengineering'), ('earth_sciences', 'Earth Sciences'), ('energy_science_engineering', 'Energy Science and Engineering'), ('environmental_science_engineering', 'Environmental Science and Engineering'), ('industrial_design_centre', 'Industrial Design Centre'), ('systems_control_engineering', 'Systems and Control Engineering'), ('climate_studies', 'Climate Studies'), ('other', 'Other')], max_length=50),
        ),
    ]
