# Generated by Django 5.2.3 on 2025-08-23 01:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_registration_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='cpi',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='CPI between 0.00 and 10.00', max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='passport_photo',
            field=models.ImageField(default=0.0, help_text='Upload passport size photo', upload_to='passport_photos/'),
            preserve_default=False,
        ),
    ]
